[env:d1_mini]
platform = espressif8266
board = d1_mini
framework = arduino
monitor_speed = 115200
upload_speed = 921600

lib_deps =
    adafruit/Adafruit NeoPixel@^1.11.0
    ArduinoJson@^6.21.0

build_flags =
    -D SERIAL_BAUD=115200
    -D LED_PIN=D4
    -D LED_COUNT=60
